// <auto-generated />
using System;
using EventEase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventEase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604200000_AddEventType")]
    partial class AddEventType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventEase.Models.Booking", b =>
            {
                b.Property<int>("BookingId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));
                b.Property<string>("BookingReference").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("EndDate").HasColumnType("datetime2");
                b.Property<int>("EventId").HasColumnType("int");
                b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                b.Property<int>("VenueId").HasColumnType("int");
                b.HasKey("BookingId");
                b.HasIndex("EventId");
                b.HasIndex("VenueId");
                b.ToTable("Bookings");
            });

            modelBuilder.Entity("EventEase.Models.Event", b =>
            {
                b.Property<int>("EventId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("EndDate").HasColumnType("datetime2");
                b.Property<int?>("EventTypeId").HasColumnType("int");
                b.Property<string>("ImageUrl").HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                b.HasKey("EventId");
                b.HasIndex("EventTypeId");
                b.ToTable("Events");

                b.HasData(
                    new { EventId = 1, Description = "An exclusive black-tie gala dinner celebrating the year's achievements.", EndDate = new DateTime(2026, 8, 15), EventTypeId = 3, ImageUrl = "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800", Name = "Annual Gala Dinner", StartDate = new DateTime(2026, 8, 15) },
                    new { EventId = 2, Description = "A two-day conference bringing together technology leaders and innovators.", EndDate = new DateTime(2026, 10, 22), EventTypeId = 1, ImageUrl = "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800", Name = "Tech Summit 2026", StartDate = new DateTime(2026, 10, 21) },
                    new { EventId = 3, Description = "A beautiful wedding reception for up to 200 guests.", EndDate = new DateTime(2026, 12, 5), EventTypeId = 2, ImageUrl = "https://images.unsplash.com/photo-1519741497674-611481863552?w=800", Name = "Wedding Celebration", StartDate = new DateTime(2026, 12, 5) }
                );
            });

            modelBuilder.Entity("EventEase.Models.EventType", b =>
            {
                b.Property<int>("EventTypeId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"));
                b.Property<string>("Description").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("EventTypeId");
                b.ToTable("EventTypes");

                b.HasData(
                    new { EventTypeId = 1, Name = "Conference",         Description = "Professional industry conferences and summits" },
                    new { EventTypeId = 2, Name = "Wedding",            Description = "Wedding ceremonies and receptions" },
                    new { EventTypeId = 3, Name = "Gala Dinner",        Description = "Formal evening dinners and award ceremonies" },
                    new { EventTypeId = 4, Name = "Corporate Meeting",  Description = "Business meetings and team-building events" },
                    new { EventTypeId = 5, Name = "Birthday & Private", Description = "Birthday parties and private celebrations" },
                    new { EventTypeId = 6, Name = "Exhibition",         Description = "Exhibitions, trade shows and product launches" }
                );
            });

            modelBuilder.Entity("EventEase.Models.Venue", b =>
            {
                b.Property<int>("VenueId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));
                b.Property<int>("Capacity").HasColumnType("int");
                b.Property<string>("ImageUrl").HasColumnType("nvarchar(max)");
                b.Property<string>("Location").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("VenueId");
                b.ToTable("Venues");

                b.HasData(
                    new { VenueId = 1, Capacity = 500, ImageUrl = "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800", Location = "123 Main Street, Johannesburg", Name = "The Grand Hall" },
                    new { VenueId = 2, Capacity = 200, ImageUrl = "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800", Location = "45 Beach Road, Cape Town",      Name = "Sunset Pavilion" },
                    new { VenueId = 3, Capacity = 300, ImageUrl = "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800", Location = "7 Innovation Drive, Pretoria",   Name = "Tech Conference Centre" }
                );
            });

            modelBuilder.Entity("EventEase.Models.Booking", b =>
            {
                b.HasOne("EventEase.Models.Event", "Event").WithMany("Bookings").HasForeignKey("EventId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("EventEase.Models.Venue", "Venue").WithMany("Bookings").HasForeignKey("VenueId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Event");
                b.Navigation("Venue");
            });

            modelBuilder.Entity("EventEase.Models.Event", b =>
            {
                b.HasOne("EventEase.Models.EventType", "EventType").WithMany("Events").HasForeignKey("EventTypeId").OnDelete(DeleteBehavior.SetNull);
                b.Navigation("EventType");
            });

            modelBuilder.Entity("EventEase.Models.Event",     b => { b.Navigation("Bookings"); });
            modelBuilder.Entity("EventEase.Models.EventType", b => { b.Navigation("Events"); });
            modelBuilder.Entity("EventEase.Models.Venue",     b => { b.Navigation("Bookings"); });
#pragma warning restore 612, 618
        }
    }
}
