using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace EventEase.Models
{
    // ViewModel used by the Booking Create + Edit forms.
    // It carries BOTH the booking fields the user is editing AND the
    // dropdown lists for Venue and Event
    public class BookingFormViewModel
    {
        // 0 means "new booking"
        public int BookingId { get; set; }

        [Required(ErrorMessage = "Please select a venue.")]
        [Display(Name = "Venue")]
        public int VenueId { get; set; }

        [Required(ErrorMessage = "Please select an event.")]
        [Display(Name = "Event")]
        public int EventId { get; set; }

        [Required(ErrorMessage = "Start date is required.")]
        // Read-only on the Edit form (auto-generated by the controller on Create).
        public string BookingReference { get; set; } = string.Empty;

        // Populated by the controller from the selected event - shown read-only
        public DateTime? EventStartDate { get; set; }
        public DateTime? EventEndDate { get; set; }

        // The controller fills these from the Venues/Events tables.
        public IEnumerable<SelectListItem> Venues { get; set; } = new List<SelectListItem>();
        public IEnumerable<SelectListItem> Events { get; set; } = new List<SelectListItem>();
    }
}
